//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FileEvent.rc
//
#define IDC_MYICON                      2
#define IDCANCEL                        2
#define IDD_FILEEVENT_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_UNEXCEPTION                 104
#define IDM_EXIT                        105
#define IDS_OUT_OF_MEM                  105
#define IDS_SYSTEM_ERROR                106
#define IDD_FIND_DLG                    106
#define IDS_ACTION_COLUMN               107
#define IDS_FILENAME_COLUMN             108
#define IDC_FILEEVENT                   109
#define IDR_MAIN_ACCEL                  109
#define IDM_MAIN                        109
#define IDS_PAUSE_MENU                  109
#define IDS_RESUME_MENU                 110
#define IDS_FILE_FILTER_CSV_1           111
#define IDS_OPEN_FILE_FAILED            112
#define IDS_SAVE_FILE_FAILED            113
#define IDS_FILE_IS_TO_LARGE            114
#define IDS_READ_FILE_FAILED            115
#define IDS_WRITE_FILE_FAILED           116
#define IDS_FILE_FILTER_CSV_2           117
#define IDS_FILE_FILTER_ALL_1           118
#define IDS_FILE_FILTER_ALL_2           119
#define IDS_INFO_FORMAT                 120
#define IDS_CAPTION_SET                 121
#define IDS_CANNOT_FIND                 122
#define IDS_CANNOT_FIND_SEL             123
#define IDS_OPEN_DIR_FAILED             124
#define IDS_MON_STOPED                  125
#define IDS_MON_STARTED                 126
#define IDS_MON_PAUSED                  127
#define IDR_MAINFRAME                   128
#define IDS_VIEW_MODE                   128
#define IDI_MAIN                        129
#define IDI_OPEN_BTN                    133
#define IDI_SAVE_BTN                    134
#define IDI_COPY_BTN                    135
#define IDI_CLEAR_BTN                   136
#define IDI_FIND_BTN                    137
#define IDI_START_BTN                   138
#define IDI_PAUSE_BTN                   139
#define IDI_STOP_BTN                    140
#define IDI_DETAILS_BTN                 141
#define IDI_OPTION_BTN                  142
#define IDB_BITMAP1                     144
#define IDB_BITMAP2                     145
#define IDD_DETAILS                     146
#define ID_EDIT_SELECTALL               147
#define IDS_FILE_ACTION_ADDED           148
#define IDS_FILE_ACTION_REMOVED         149
#define IDD_DIALOG1                     149
#define IDD_MONITOR_OPTIONS             149
#define IDS_FILE_ACTION_MODIFIED        150
#define IDR_ITEM_MENU                   150
#define IDS_FILE_ACTION_RENAMED_OLD_NAME 151
#define IDS_FILE_ACTION_RENAMED_NEW_NAME 152
#define IDS_UNKNOWN_ACTION              153
#define IDS_MONITOR_FAILED              154
#define IDC_INFO                        1000
#define IDC_PATH                        1001
#define IDC_BUTTON1                     1002
#define IDC_BROWSE                      1002
#define IDC_SUBTREE                     1003
#define IDC_CHECK1                      1004
#define IDC_FILE_NOTIFY_CHANGE_FILE_NAME 1004
#define IDC_CHECK2                      1005
#define IDC_FILE_NOTIFY_CHANGE_DIR_NAME 1005
#define IDC_CHECK3                      1006
#define IDC_RADIO1                      1007
#define IDC_FILE_NOTIFY_CHANGE_ATTRIBUTES 1007
#define IDC_RADIO2                      1008
#define IDC_FILE_NOTIFY_CHANGE_SIZE     1008
#define IDC_RADIO3                      1009
#define IDC_FILE_NOTIFY_CHANGE_LAST_WRITE 1009
#define IDC_RADIO4                      1010
#define IDC_FILE_NOTIFY_CHANGE_LAST_ACCESS 1010
#define IDC_FILE_NOTIFY_CHANGE_CREATION 1011
#define IDC_CHECK9                      1012
#define IDC_FILE_NOTIFY_CHANGE_SECURITY 1012
#define IDC_FINDTEXT                    1150
#define IDC_WORD_ONLY                   1151
#define IDD_GENERAL                     30724
#define ID_Menu                         32771
#define ID_FILE_SAVE                    32772
#define ID_Menu32773                    32773
#define ID_FILE_OPEN                    32774
#define ID_FILE_SAVE_AS                 32775
#define ID_VIEW_REFRESH                 32776
#define ID_EDIT_FINDNEXT                32777
#define ID_MONITOR_START                32778
#define ID_MONITOR_STOP                 32779
#define ID_MONITOR_FILTER               32780
#define ID_EDIT_COPY                    32781
#define ID_EDIT_FIND                    32782
#define ID_EDIT_FINDPREVIOUS            32783
#define ID_VIEW_PROPERTIES              32784
#define ID_VIEW_OPTIONS                 32785
#define ID_MONITOR_PAUSE                32786
#define ID_VIEW_DETAILS                 32787
#define ID_MONITOR_START32788           32788
#define ID_MONITOR_RESUME               32788
#define ID_EDIT_CLEAR                   32789
#define ID_FILE_EXIT                    32808
#define ID_HELP_ABOUT                   32809
#define IDS_IDLE_STATUS                 32810
#define ID_Menu32813                    32813
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
